### ISSUE TITLE
Media Source Extensions

### ISSUE THREAD

**Issue by heff** [gmarty/DVD.js#1]
Great JSConf talk!

Just wondering if you've considered working media source extensions into this workflow.

**Comment by gmarty** [comment]
Hey! Sorry for the delay.
Yes, the first prototype that attempts to read a DVD on the fly used to use Media Source Extension for a seamless playback of the video bits sent by the server to the browser (see `master` branch).
However, this approach has been deprecated in favour of a DVD converter (in `converter` branch).

I promise I'll add a README to both branches to make things clearer!

**Comment by heff** [comment]
Ha, no worries. I remember that part from your talk now. Anyway, very cool project!
